### ISSUE TITLE
Broken with unknown/broken buffer

### ISSUE THREAD

**Issue by evilebottnawi** [sindresorhus/is-gif#2]
Input:
```
const isGif = require('is-gif');

console.log(isGif('foo'));
```

throw `TypeError: Cannot read property 'ext' of null`.

After upgrade on `2.0.0` version some package have problem, example https://github.com/imagemin/imagemin-gifsicle/issues/27

/cc @sindresorhus

**Comment by evilebottnawi** [comment]
Oh, it is break many imagemin configuration (where used `imagemin-svgo` and `imagemin-gifsicle`) in many popular boilerplate because any `svg` image pass as string

**Comment by sindresorhus** [comment]
The documentation clearly states (and has always stated) that it accepts the following types:

> Type: `Buffer` `Uint8Array`

You're trying to fix this problem in the wrong place.

**Comment by sindresorhus** [comment]
That being said, from reading https://github.com/imagemin/imagemin-gifsicle/issues/27, it seem you're actually passing in strings converted to a buffer, which should be fixed in v3 :)
